server:
  port: 8081

feign:
  okhttp:
    enabled: true
  command:
      default:
        execution:
          isolation:
            thread:
              timeoutInMilliseconds: 5000
ribbon:  
   ReadTimeout: 6000
   ConnectTimeout: 6000
                  
spring:
  application:
    name: pachira-oauth2
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        preferIpAddress: true
        instanceId: ${spring.application.name}@${spring.cloud.client.ip-address}:${server.port}