server:
  port: 8082
  tomcat:
    min-spare-threads: 20
    max-threads: 100

feign:
  okhttp:
    enabled: true
  command:
      default:
        execution:
          isolation:
            thread:
              timeoutInMilliseconds: 5000
              
ribbon:  
   ReadTimeout: 6000
   ConnectTimeout: 6000
     
spring:
  application:
    name: pachira-scheduler
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        preferIpAddress: true
        instanceId: ${spring.application.name}@${spring.cloud.client.ip-address}:${server.port}

  datasource:
    url: jdbc:mysql://localhost:3306/pachira_scheduler?useUnicode=true&characterEncoding=utf-8&useSSL=false
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: 111111

jwt:
  key: ABCDEF

mybatis:
  config-location: classpath:mybatis-config.xml
  
zookeeper:
  address: localhost:2181