server:
  port: 8080
  
spring:
  application:
    name: pachira-party
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        preferIpAddress: true
        instanceId: ${spring.application.name}@${spring.cloud.client.ip-address}:${server.port}